name: Build, Test, and Deploy to Azure Web App - nutritionalservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      # Set up Java and Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Build the project
      - name: Build the Project
        run: ./gradlew bootJar -x test --no-daemon

      # Run unit tests in the testing module and generate Jacoco report
      - name: Run Tests and Generate Jacoco Report
        run: |
          ./gradlew :testingModule:test
          ./gradlew jacocoRootReport

      - name: Debug - List contents of build/libs
        run: ls -l build/libs

    # Upload the artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FD394C40460B451B9300DDB2B6DD8209 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48A31D85D455405B8716C3C5E2E3B7B7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_025B760EC9EC48D28960EB14E3852072 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nutritionalservice'
          slot-name: 'Production'
          package: '*.jar'
