name: Build, Test, and Deploy to Azure Web App - nutritionalservice

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      # Set up Java and Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '8.11.1'

      # Build the project
      - name: Build the Project
        run: ./gradlew bootJar -x test --no-daemon

      - name: Debug - List contents of build/libs
        run: ls -l webApi/build/libs

      # Run unit tests in the testing module and generate Jacoco report
      - name: Run Tests and Generate Jacoco Report
        run: |
          ./gradlew :testingModule:test
          ./gradlew jacocoRootReport

    # Upload the artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: webApi/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B75E5EDFCA5C4763B284D95445EADB47 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_910AB614D2C44E08AC8FB2CF56C2E748 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51C15D576F3D426DA53EE760D7AC4EF1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nutritional-service'
          slot-name: 'Production'
          package: '*.jar'
